openapi: 3.0.3
info:
    title: User API
    description: API for managing users
    version: 1.0.0
paths:
    /users:
        get:
            summary: Get a list of users
            description: Retrieve a list of users.
            tags:
                - Users
            security:
                - public: []
            responses:
                '200':
                    description: A list of users
        post:
            summary: Register a new user
            description: Register a new user.
            tags:
                - Users
            security:
                - public: []
            parameters:
                - in: body
                  name: user
                  description: User registration data
                  required: true
                  schema:
                      $ref: '#/components/schemas/UserInput'
            responses:
                '201':
                    description: User registered successfully
    /users/{pid}:
        get:
            summary: Get a user by ID
            description: Retrieve a user by its ID.
            tags:
                - Users
            security:
                - public: []
            parameters:
                - in: path
                  name: pid
                  required: true
                  schema:
                      type: string
                  description: ID of the user
            responses:
                '200':
                    description: The requested user
        put:
            summary: Update a user by ID
            description: Update a user by its ID.
            tags:
                - Users
            parameters:
                - in: path
                  name: pid
                  required: true
                  schema:
                      type: string
                  description: ID of the user
                - in: body
                  name: user
                  description: Updated user data
                  required: true
                  schema:
                      $ref: '#/components/schemas/UserInput'
            responses:
                '200':
                    description: User updated successfully
        delete:
            summary: Delete a user by ID
            description: Delete a user by its ID.
            tags:
                - Users
            parameters:
                - in: path
                  name: pid
                  required: true
                  schema:
                      type: string
                  description: ID of the user
            responses:
                '204':
                    description: User deleted successfully
components:
    schemas:
        UserInput:
            type: object
            properties: // Define properties for the UserInput schema as needed
