export { ArticleRouter } from './articles/index.js'
export { CategoryRouter } from './categories/index.js'
export { CitiesRouter as CitiyRouter } from './cities/index.js'
export { CommentRouter } from './comments/index.js'
export { FileRouter } from './files/index.js'
export { MaterialRouter } from './materials/index.js'
export { UserRouter } from './users/index.js'
