openapi: 3.0.3
info:
    title: Category API
    description: API for managing categories
    version: 1.0.0
paths:
    /categories:
        get:
            summary: Get a list of categories
            description: Retrieve a list of categories.
            tags:
                - Categories
            security:
                - public: []
            responses:
                '200':
                    description: A list of categories
        post:
            summary: Create a new category
            description: Create a new category.
            tags:
                - Categories
            security:
                - public: []
            responses:
                '201':
                    description: Category created successfully
    /categories/{fid}:
        get:
            summary: Get a category by ID
            description: Retrieve a category by its ID.
            tags:
                - Categories
            security:
                - public: []
            parameters:
                - in: path
                  name: fid
                  required: true
                  schema:
                      type: string
                  description: ID of the category
            responses:
                '200':
                    description: The requested category
        put:
            summary: Update a category by ID
            description: Update a category by its ID.
            tags:
                - Categories
            security:
                - public: []
            parameters:
                - in: path
                  name: fid
                  required: true
                  schema:
                      type: string
                  description: ID of the category
                - in: requestBody
                  name: body
                  required: true
                  description: Updated category data
                  content:
                      application/json:
                          schema:
                              $ref: '#/components/schemas/CategoryInput'
            responses:
                '200':
                    description: Category updated successfully
        delete:
            summary: Delete a category by ID
            description: Delete a category by its ID.
            tags:
                - Categories
            security:
                - public: []
            parameters:
                - in: path
                  name: fid
                  required: true
                  schema:
                      type: string
                  description: ID of the category
            responses:
                '204':
                    description: Category deleted successfully
components:
    schemas:
        CategoryInput:
            type: object
            properties: // Define properties for the CategoryInput schema as needed
